// <auto-generated />
namespace EE3206_WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class appoinement_Time_Cange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appoinement_Time_Cange));
        
        string IMigrationMetadata.Id
        {
            get { return "202112150856507_appoinement_Time_Cange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
